### ISSUE TITLE
Tag a 1.0.6 release?

### ISSUE THREAD

**Issue by ptlis** [jcchavezs/zipkin-symfony#12]
I'm testing this bundle for use across our Symfony projects and ran into a bug in the current release (1.0.5 at time of writing) that is [fixed in master](https://github.com/jcchavezs/zipkin-symfony/commit/59f1bcbcfd1341a44efa4442ed271904f5e47885#diff-815bc2a1e745ffcfbe5a4d4b0bb01b5a) (the removal of $logger as an argument when constructing an Http instance).

I'm not comfortable targeting dev-master on production systems, so tagging a release that includes the above fix would be very much appreciated.

**Comment by jcchavezs** [comment]
@ptlis thanks for opening this. I will be creating a tag for today. Sorry for the inconveniences.

**Comment by ptlis** [comment]
Great, thanks for the quick response!

**Comment by jcchavezs** [comment]
Done! https://github.com/jcchavezs/zipkin-symfony/tree/1.0.6
